import type {
  Aktivitet,
  Anvandare,
  Arende,
  Arendekategori,
  Aviseringsinstallning,
  Bokning,
  EpostMottagare,
  Kund,
  Kundanteckning,
  Meddelande,
  Standardsvar,
} from '@/lib/types'

/**
 * DEMODATA
 * ────────────────────────────────────────────────────────────────────────────
 * All data i denna fil är påhittad testdata för demonstrationssyfte.
 * Vid övergång till riktig databas ersätts denna fil av databasmigrationer
 * och seed-skript. Ingen annan del av koden importerar denna fil direkt –
 * allt går via `lib/store.ts`.
 */

/** Relativa tidsstämplar så att demon alltid känns aktuell. */
const nu = new Date()

function tidsstampel(dagarSedan: number, timmar = 9, minuter = 0): string {
  const d = new Date(nu)
  d.setDate(d.getDate() - dagarSedan)
  d.setHours(timmar, minuter, 0, 0)
  return d.toISOString()
}

function timmarSedan(antal: number): string {
  const d = new Date(nu.getTime() - antal * 3600_000)
  return d.toISOString()
}

function datumOm(dagar: number): string {
  const d = new Date(nu)
  d.setDate(d.getDate() + dagar)
  return d.toISOString().slice(0, 10)
}

export const iDag = new Date(nu).toISOString().slice(0, 10)

// ─── Användare ──────────────────────────────────────────────────────────────

export const demoAnvandare: Anvandare[] = [
  {
    id: 'u-1',
    namn: 'Anna Lindqvist',
    epost: 'admin@nova-it.se',
    roll: 'administrator',
    initialer: 'AL',
    titel: 'Verksamhetsansvarig',
    aktiv: true,
  },
  {
    id: 'u-2',
    namn: 'Marcus Ek',
    epost: 'tekniker@nova-it.se',
    roll: 'tekniker',
    initialer: 'ME',
    titel: 'IT-tekniker',
    aktiv: true,
  },
  {
    id: 'u-3',
    namn: 'Sofia Bergström',
    epost: 'sofia@nova-it.se',
    roll: 'tekniker',
    initialer: 'SB',
    titel: 'IT-tekniker, nätverk',
    aktiv: true,
  },
  {
    id: 'u-4',
    namn: 'Johan Nyström',
    epost: 'johan@nova-it.se',
    roll: 'tekniker',
    initialer: 'JN',
    titel: 'Tekniker, deltid',
    aktiv: false,
  },
]

// ─── Kunder ─────────────────────────────────────────────────────────────────

export const demoKunder: Kund[] = [
  {
    id: 'k-1',
    namn: 'Birgitta Sandell',
    kundtyp: 'privatperson',
    epost: 'birgitta.sandell@telia.com',
    telefon: '070-412 88 31',
    adress: 'Loviselundsvägen 42',
    ort: 'Hässelby',
    senasteKontakt: timmarSedan(3),
    interntAnteckning:
      'Föredrar telefonkontakt före e-post. Har äldre HP-laptop med mekanisk hårddisk.',
    skapad: tidsstampel(420),
  },
  {
    id: 'k-2',
    namn: 'Café Vinden',
    kundtyp: 'verksamhet',
    organisation: 'Café Vinden Handelsbolag',
    orgnummer: '969789-1122',
    epost: 'info@cafevinden.se',
    telefon: '08-511 22 90',
    adress: 'Bergslagsvägen 12',
    ort: 'Vällingby',
    kontaktperson: 'Peter Åkesson',
    senasteKontakt: timmarSedan(20),
    interntAnteckning:
      'Kassasystem via Wi-Fi. Kritiskt att uppkopplingen fungerar under lunchtid 11–14.',
    skapad: tidsstampel(300),
  },
  {
    id: 'k-3',
    namn: 'Lars Hedlund',
    kundtyp: 'privatperson',
    epost: 'lars.hedlund@gmail.com',
    telefon: '073-559 04 17',
    adress: 'Astrakangatan 7',
    ort: 'Hässelby Gård',
    senasteKontakt: timmarSedan(48),
    skapad: tidsstampel(190),
  },
  {
    id: 'k-4',
    namn: 'Bromma Redovisning',
    kundtyp: 'verksamhet',
    organisation: 'Bromma Redovisningsbyrå AB',
    orgnummer: '556712-4408',
    epost: 'kontakt@brommaredovisning.se',
    telefon: '08-704 15 60',
    adress: 'Gustavslundsvägen 141',
    ort: 'Bromma',
    kontaktperson: 'Helena Wikström',
    senasteKontakt: timmarSedan(6),
    interntAnteckning:
      'Microsoft 365 Business Premium, 9 licenser. Har haft återkommande problem med delade postlådor.',
    skapad: tidsstampel(240),
  },
  {
    id: 'k-5',
    namn: 'Ingrid Molin',
    kundtyp: 'privatperson',
    epost: 'ingrid.molin@hotmail.se',
    telefon: '076-231 77 05',
    adress: 'Maltesholmsvägen 88',
    ort: 'Hässelby Strand',
    senasteKontakt: timmarSedan(30),
    interntAnteckning: 'Behöver extra tydliga instruktioner. Tacksam för skriftlig sammanfattning.',
    skapad: tidsstampel(95),
  },
  {
    id: 'k-6',
    namn: 'Vällingby Fastighetsservice',
    kundtyp: 'verksamhet',
    organisation: 'Vällingby Fastighetsservice AB',
    orgnummer: '559102-8871',
    epost: 'drift@vallingbyfast.se',
    telefon: '08-620 41 12',
    adress: 'Solursgången 3',
    ort: 'Vällingby',
    kontaktperson: 'Tomas Krister',
    senasteKontakt: timmarSedan(72),
    skapad: tidsstampel(140),
  },
  {
    id: 'k-7',
    namn: 'Fredrik Sjöberg',
    kundtyp: 'privatperson',
    epost: 'fredrik.sjoberg@outlook.com',
    telefon: '070-882 19 44',
    adress: 'Skattegårdsvägen 21',
    ort: 'Vinsta',
    senasteKontakt: timmarSedan(96),
    skapad: tidsstampel(60),
  },
  {
    id: 'k-8',
    namn: 'Hässelby Konstförening',
    kundtyp: 'verksamhet',
    organisation: 'Hässelby Konstförening',
    orgnummer: '802441-9930',
    epost: 'styrelsen@hasselbykonst.se',
    telefon: '08-38 44 21',
    adress: 'Hässelby Torg 5',
    ort: 'Hässelby',
    kontaktperson: 'Margareta Dahl',
    senasteKontakt: timmarSedan(150),
    interntAnteckning: 'Ideell förening, begränsad budget. Godkänner alltid kostnad i förväg.',
    skapad: tidsstampel(75),
  },
]

// ─── Kundanteckningar ───────────────────────────────────────────────────────

/**
 * Interna anteckningar per kund, som en egen tabell istället för ett enda
 * fritextfält. Seedas från kundernas ursprungliga `interntAnteckning` så att
 * inget befintligt innehåll försvinner, plus några kompletterande noteringar.
 */
export const demoKundanteckningar: Kundanteckning[] = [
  ...demoKunder
    .filter((k) => k.interntAnteckning)
    .map((k, i) => ({
      id: `kant-seed-${i + 1}`,
      kundId: k.id,
      text: k.interntAnteckning as string,
      forfattare: 'Anna Lindqvist',
      skapad: tidsstampel(30 + i * 4, 10, 15),
    })),
  {
    id: 'kant-10',
    kundId: 'k-2',
    text: 'Bytte till fast kanal på 5 GHz för kassasystemet. Kontrollera igen vid nästa besök.',
    forfattare: 'Sofia Bergström',
    skapad: tidsstampel(9, 14, 30),
  },
  {
    id: 'kant-11',
    kundId: 'k-4',
    text: 'Helena vill ha samlad faktura per kvartal. Godkänt av ekonomi.',
    forfattare: 'Anna Lindqvist',
    skapad: tidsstampel(4, 8, 45),
  },
  {
    id: 'kant-12',
    kundId: 'k-1',
    text: 'Ringde för uppföljning efter genomgången av datorn – kunden är nöjd med resultatet.',
    forfattare: 'Marcus Ek',
    skapad: timmarSedan(26),
  },
  {
    id: 'kant-13',
    kundId: 'k-6',
    text: 'Nyckelkvittens finns hos Tomas. Anmäl alltid besök i receptionen först.',
    forfattare: 'Sofia Bergström',
    skapad: tidsstampel(15, 13, 5),
  },
]

// ─── Ärenden ────────────────────────────────────────────────────────────────

export const demoArenden: Arende[] = [
  {
    id: 'a-1',
    arendenummer: 'NIT-2418',
    rubrik: 'Långsam bärbar dator, tar flera minuter att starta',
    kundId: 'k-1',
    kundNamn: 'Birgitta Sandell',
    kundtyp: 'privatperson',
    epost: 'birgitta.sandell@telia.com',
    telefon: '070-412 88 31',
    kategori: 'datorer_vardags_it',
    underkategori: 'Prestanda och långsamhet',
    status: 'pagaende',
    prioritet: 'normal',
    ansvarigId: 'u-2',
    kanal: 'supportassistent',
    beskrivning:
      'Min laptop har blivit väldigt långsam det senaste halvåret. Den tar ungefär fem minuter innan jag kan börja använda den efter att jag slagit på den, och sen hänger den sig när jag har flera flikar öppna i webbläsaren. Den är kanske sex år gammal. Jag använder den mest till internetbank, mejl och att titta på SVT Play.',
    assistentSammanfattning:
      'Kunden beskriver kraftigt försämrad prestanda på cirka 6 år gammal bärbar dator. Symtom: lång starttid (~5 min), programhängningar vid flerflikad webbläsning. Sannolika orsaker: mekanisk hårddisk nära slutet av livslängden, fragmentering, för lite RAM, eller ansamlade autostartprogram. Föreslagen åtgärd: kontrollera SMART-status, utvärdera uppgradering till SSD samt RAM. Kunden har inte nämnt datatförlust – backup bör verifieras före ingrepp.',
    bilagor: [
      {
        id: 'b-1',
        namn: 'aktivitetshanteraren.png',
        storlek: '284 kB',
        typ: 'image/png',
        uppladdad: timmarSedan(30),
      },
    ],
    skapad: timmarSedan(31),
    uppdaterad: timmarSedan(3),
    sistaSvar: timmarSedan(3),
  },
  {
    id: 'a-2',
    arendenummer: 'NIT-2417',
    rubrik: 'Trådlöst nätverk tappar anslutning under lunchrusningen',
    kundId: 'k-2',
    kundNamn: 'Café Vinden',
    kundtyp: 'verksamhet',
    organisation: 'Café Vinden Handelsbolag',
    epost: 'info@cafevinden.se',
    telefon: '08-511 22 90',
    kategori: 'natverk_wifi',
    underkategori: 'Instabil anslutning',
    status: 'pagaende',
    prioritet: 'kritisk',
    ansvarigId: 'u-3',
    kanal: 'telefon',
    beskrivning:
      'Vårt kassasystem tappar kontakten med nätet flera gånger varje dag, framför allt mellan elva och två när det är mycket folk. Då kan vi inte ta kort och det blir kö direkt. Vi har en router från Telia och en extra accesspunkt i taket vid köket. Detta måste lösas snabbt, vi tappar försäljning.',
    assistentSammanfattning:
      'Verksamhetskritiskt nätverksproblem. Kassasystemet tappar anslutning återkommande under högtrafik (11–14), vilket blockerar kortbetalning. Miljö: operatörsrouter (Telia) plus en extern accesspunkt. Hypoteser: kanalöverlappning/störning i 2,4 GHz, otillräcklig kapacitet vid många gästenheter, eller att gästtrafik och kassa delar samma nät utan prioritering. Rekommenderas: platsbesök med kanalanalys, separering av kassa på eget SSID/VLAN.',
    bilagor: [],
    skapad: timmarSedan(26),
    uppdaterad: timmarSedan(20),
    sistaSvar: timmarSedan(20),
  },
  {
    id: 'a-3',
    arendenummer: 'NIT-2421',
    rubrik: 'Installation av ny dator och flytt av filer',
    kundId: 'k-3',
    kundNamn: 'Lars Hedlund',
    kundtyp: 'privatperson',
    epost: 'lars.hedlund@gmail.com',
    telefon: '073-559 04 17',
    kategori: 'installation',
    underkategori: 'Ny dator och dataflytt',
    status: 'bokad',
    prioritet: 'normal',
    ansvarigId: 'u-2',
    kanal: 'kontaktformular',
    beskrivning:
      'Jag har köpt en ny stationär dator från Webhallen men vågar inte flytta över allt själv. Jag har bilder och dokument på den gamla datorn som jag absolut inte får tappa, plus att jag vill ha kvar mitt Office och min skrivare. Kan någon komma hem och hjälpa till med hela installationen?',
    assistentSammanfattning:
      'Kunden önskar fullständig installation av ny stationär dator inklusive migrering av personliga filer (bilder, dokument), återinstallation av Office samt konfiguration av skrivare. Kunden uttrycker uttalad oro för dataförlust. Rekommenderas: hembesök med verifierad backup före migrering.',
    bilagor: [
      {
        id: 'b-2',
        namn: 'kvitto-webhallen.pdf',
        storlek: '112 kB',
        typ: 'application/pdf',
        uppladdad: tidsstampel(2, 14),
      },
    ],
    skapad: tidsstampel(2, 13, 20),
    uppdaterad: timmarSedan(48),
    sistaSvar: timmarSedan(48),
  },
  {
    id: 'a-4',
    arendenummer: 'NIT-2423',
    rubrik: 'Misstänkt virus efter nedladdning, varningar på skärmen',
    kundId: 'k-5',
    kundNamn: 'Ingrid Molin',
    kundtyp: 'privatperson',
    epost: 'ingrid.molin@hotmail.se',
    telefon: '076-231 77 05',
    kategori: 'sakerhet_virus',
    underkategori: 'Skadlig kod och varningar',
    status: 'ny',
    prioritet: 'hog',
    ansvarigId: null,
    kanal: 'supportassistent',
    beskrivning:
      'Det kommer upp rutor hela tiden som säger att datorn är infekterad och att jag ska ringa ett nummer. Jag laddade ner ett program för att öppna en PDF igår. Nu går det inte att stänga rutorna och jag vågar inte använda internetbanken. Jag har inte ringt numret.',
    assistentSammanfattning:
      'Sannolik adware/scareware-infektion efter nedladdning av tredjepartsprogram. Kunden rapporterar återkommande popup-varningar med uppmaning att ringa ett telefonnummer – klassiskt mönster för teknisk supportbedrägeri. Kunden har korrekt avstått från att ringa. Prioriterat: koppla ner från nätet vid behov, granska nyligen installerade program och webbläsartillägg, kör fullständig genomsökning. Kunden bör inte använda internetbank innan datorn är verifierad ren.',
    bilagor: [
      {
        id: 'b-3',
        namn: 'popup-varning.jpg',
        storlek: '651 kB',
        typ: 'image/jpeg',
        uppladdad: timmarSedan(5),
      },
      {
        id: 'b-4',
        namn: 'installerade-program.png',
        storlek: '198 kB',
        typ: 'image/png',
        uppladdad: timmarSedan(5),
      },
    ],
    skapad: timmarSedan(5),
    uppdaterad: timmarSedan(5),
  },
  {
    id: 'a-5',
    arendenummer: 'NIT-2422',
    rubrik: 'Microsoft 365 – delad postlåda syns inte för nya medarbetare',
    kundId: 'k-4',
    kundNamn: 'Bromma Redovisning',
    kundtyp: 'verksamhet',
    organisation: 'Bromma Redovisningsbyrå AB',
    epost: 'kontakt@brommaredovisning.se',
    telefon: '08-704 15 60',
    kategori: 'konton_moln_sakerhet',
    underkategori: 'Microsoft 365 och behörigheter',
    status: 'vantar_pa_kund',
    prioritet: 'hog',
    ansvarigId: 'u-3',
    kanal: 'e-post',
    beskrivning:
      'Vi har anställt två nya redovisningskonsulter. De kommer åt sin egen mejl men ser inte den delade brevlådan kund@brommaredovisning.se, som alla andra ser. Vi har också problem med att de inte kan öppna dokument i den delade SharePoint-mappen för årsbokslut. Det är ganska bråttom, det är högsäsong.',
    assistentSammanfattning:
      'Behörighetsproblem i Microsoft 365 för två nyupplagda konton. Två separata symtom: (1) delad postlåda kund@brommaredovisning.se visas inte i Outlook, (2) åtkomst nekas till SharePoint-bibliotek för årsbokslut. Trolig orsak: kontona saknar medlemskap i relevant säkerhetsgrupp, alternativt att licens/behörighet inte hunnit replikera. Åtgärd kräver global administratörsåtkomst hos kunden.',
    bilagor: [],
    skapad: tidsstampel(3, 8, 45),
    uppdaterad: timmarSedan(6),
    sistaSvar: timmarSedan(6),
  },
  {
    id: 'a-6',
    arendenummer: 'NIT-2419',
    rubrik: 'Nätverksproblem – ingen uppkoppling i två kontorsrum',
    kundId: 'k-6',
    kundNamn: 'Vällingby Fastighetsservice',
    kundtyp: 'verksamhet',
    organisation: 'Vällingby Fastighetsservice AB',
    epost: 'drift@vallingbyfast.se',
    telefon: '08-620 41 12',
    kategori: 'natverk_wifi',
    underkategori: 'Kabelnät och switchar',
    status: 'pagaende',
    prioritet: 'hog',
    ansvarigId: 'u-3',
    kanal: 'kontaktformular',
    beskrivning:
      'Efter att vi byggde om kontoret i somras har två av rummen ingen uppkoppling alls i nätverksuttagen. Wi-Fi fungerar men vi har stationära datorer där som behöver kabel. Vi vet inte om kablarna är trasiga eller om det är switchen i serverskåpet som är fel. Det finns ett patchpanel-skåp i korridoren.',
    assistentSammanfattning:
      'Kabelbaserad nätverksanslutning saknas i två kontorsrum efter ombyggnation. Wi-Fi fungerar, vilket indikerar att problemet är begränsat till kabelinfrastruktur snarare än internetförbindelsen. Möjliga orsaker: kablar avklippta/omkopplade vid ombyggnation, opatchade portar i patchpanel, eller inaktiverade switchportar. Kräver platsbesök med kabeltestare.',
    bilagor: [
      {
        id: 'b-5',
        namn: 'serverskap.jpg',
        storlek: '1,2 MB',
        typ: 'image/jpeg',
        uppladdad: tidsstampel(5, 11),
      },
    ],
    skapad: tidsstampel(5, 10, 15),
    uppdaterad: timmarSedan(72),
    sistaSvar: timmarSedan(72),
  },
  {
    id: 'a-7',
    arendenummer: 'NIT-2424',
    rubrik: 'Skrivaren svarar inte efter Windows-uppdatering',
    kundId: 'k-7',
    kundNamn: 'Fredrik Sjöberg',
    kundtyp: 'privatperson',
    epost: 'fredrik.sjoberg@outlook.com',
    telefon: '070-882 19 44',
    kategori: 'datorer_vardags_it',
    underkategori: 'Skrivare och kringutrustning',
    status: 'ny',
    prioritet: 'normal',
    ansvarigId: null,
    kanal: 'kontaktformular',
    beskrivning:
      'Min Brother-skrivare slutade fungera i förrgår, precis efter att Windows hade uppdaterat sig själv. Datorn hittar den inte längre, varken via USB eller trådlöst. Jag har startat om både datorn och skrivaren flera gånger.',
    assistentSammanfattning:
      'Skrivaren (Brother) upptäcks inte efter Windows-uppdatering, oavsett anslutningssätt (USB och trådlöst). Kunden har redan utfört omstart av båda enheterna. Trolig orsak: drivrutin som skrivits över eller inaktiverats vid uppdateringen, alternativt att utskriftshanteraren har fastnat. Bedöms lösbar via distanssupport.',
    bilagor: [],
    skapad: timmarSedan(11),
    uppdaterad: timmarSedan(11),
  },
  {
    id: 'a-8',
    arendenummer: 'NIT-2416',
    rubrik: 'Backup av föreningens dokument och bildarkiv',
    kundId: 'k-8',
    kundNamn: 'Hässelby Konstförening',
    kundtyp: 'verksamhet',
    organisation: 'Hässelby Konstförening',
    epost: 'styrelsen@hasselbykonst.se',
    telefon: '08-38 44 21',
    kategori: 'konton_moln_sakerhet',
    underkategori: 'Backup och återställning',
    status: 'vantar_pa_kund',
    prioritet: 'lag',
    ansvarigId: 'u-2',
    kanal: 'kontaktformular',
    beskrivning:
      'Föreningen har protokoll, medlemsregister och ett stort bildarkiv från våra utställningar sedan 2009. Allt ligger på en gammal extern hårddisk hos kassören. Vi vill ha en tryggare lösning men har begränsad budget. Vad rekommenderar ni?',
    assistentSammanfattning:
      'Rådgivningsärende gällande backup för ideell förening. Nuvarande läge: enda kopian av protokoll, medlemsregister och bildarkiv (2009–) finns på en enskild extern hårddisk, vilket innebär betydande risk för total dataförlust. Budget är begränsad. Förslag att utvärdera: molnlagring med versionshantering plus en lokal kopia enligt 3-2-1-principen. GDPR-aspekt att beakta eftersom medlemsregister ingår.',
    bilagor: [],
    skapad: tidsstampel(7, 16, 30),
    uppdaterad: timmarSedan(150),
    sistaSvar: timmarSedan(150),
  },
  {
    id: 'a-9',
    arendenummer: 'NIT-2412',
    rubrik: 'Wi-Fi når inte ut till sovrummet',
    kundId: 'k-1',
    kundNamn: 'Birgitta Sandell',
    kundtyp: 'privatperson',
    epost: 'birgitta.sandell@telia.com',
    telefon: '070-412 88 31',
    kategori: 'natverk_wifi',
    underkategori: 'Täckning och räckvidd',
    status: 'lost',
    prioritet: 'lag',
    ansvarigId: 'u-3',
    kanal: 'telefon',
    beskrivning:
      'Jag har ingen täckning i sovrummet där jag brukar läsa på iPaden. Routern står i hallen.',
    assistentSammanfattning:
      'Täckningsproblem i lägenhet. Åtgärdat genom omplacering av router samt komplettering med mesh-enhet.',
    bilagor: [],
    skapad: tidsstampel(24, 10),
    uppdaterad: tidsstampel(21, 15),
    sistaSvar: tidsstampel(21, 15),
  },
  {
    id: 'a-10',
    arendenummer: 'NIT-2408',
    rubrik: 'Uppgradering till SSD och mer minne',
    kundId: 'k-3',
    kundNamn: 'Lars Hedlund',
    kundtyp: 'privatperson',
    epost: 'lars.hedlund@gmail.com',
    telefon: '073-559 04 17',
    kategori: 'datorer_vardags_it',
    underkategori: 'Uppgradering av hårdvara',
    status: 'stangd',
    prioritet: 'normal',
    ansvarigId: 'u-2',
    kanal: 'kontaktformular',
    beskrivning:
      'Vill uppgradera min gamla laptop innan jag bestämmer mig för att köpa ny. Går det?',
    bilagor: [],
    skapad: tidsstampel(41, 9),
    uppdaterad: tidsstampel(36, 14),
    sistaSvar: tidsstampel(36, 14),
  },
  {
    id: 'a-11',
    arendenummer: 'NIT-2425',
    rubrik: 'Kan inte logga in på Microsoft-kontot efter telefonbyte',
    kundId: 'k-4',
    kundNamn: 'Bromma Redovisning',
    kundtyp: 'verksamhet',
    organisation: 'Bromma Redovisningsbyrå AB',
    epost: 'kontakt@brommaredovisning.se',
    telefon: '08-704 15 60',
    kategori: 'konton_moln_sakerhet',
    underkategori: 'Tvåfaktorsautentisering',
    status: 'ny',
    prioritet: 'kritisk',
    ansvarigId: null,
    kanal: 'telefon',
    beskrivning:
      'En av våra konsulter bytte telefon i helgen och har inte kvar sin autentiseringsapp. Hon kommer inte in i Outlook eller i affärssystemet alls nu, och hon har deklarationer som ska in denna vecka. Vi behöver hjälp omgående.',
    assistentSammanfattning:
      'Användare utelåst från Microsoft 365 efter telefonbyte – autentiseringsappen migrerades inte och MFA-metoden är därmed otillgänglig. Verksamhetspåverkan: användaren saknar åtkomst till e-post och affärssystem under pågående deklarationsperiod. Åtgärd: återställ MFA-metod via global administratör och registrera ny enhet. Identiteten på användaren måste verifieras innan återställning.',
    bilagor: [],
    skapad: timmarSedan(2),
    uppdaterad: timmarSedan(2),
  },
  {
    id: 'a-12',
    arendenummer: 'NIT-2420',
    rubrik: 'Ny arbetsplats till nyanställd – dator, konto och behörigheter',
    kundId: 'k-6',
    kundNamn: 'Vällingby Fastighetsservice',
    kundtyp: 'verksamhet',
    organisation: 'Vällingby Fastighetsservice AB',
    epost: 'drift@vallingbyfast.se',
    telefon: '08-620 41 12',
    kategori: 'installation',
    underkategori: 'Arbetsplats och onboarding',
    status: 'bokad',
    prioritet: 'normal',
    ansvarigId: 'u-2',
    kanal: 'e-post',
    beskrivning:
      'Vi får en ny driftstekniker som börjar om två veckor. Behöver en komplett arbetsplats: laptop, konto, mejl, tillgång till våra delade mappar och installation av vårt fastighetssystem. Kan ni sätta upp allt innan hon börjar?',
    assistentSammanfattning:
      'Onboarding av ny medarbetare med tydligt startdatum. Omfattning: klientdator, användarkonto och e-post, behörighet till delade mappar samt installation av verksamhetssystem för fastighetsförvaltning. Bör planeras med marginal före tillträdesdatum.',
    bilagor: [],
    skapad: tidsstampel(4, 11, 10),
    uppdaterad: timmarSedan(40),
    sistaSvar: timmarSedan(40),
  },
]

// ─── Meddelanden ────────────────────────────────────────────────────────────

export const demoMeddelanden: Meddelande[] = [
  {
    id: 'm-1',
    arendeId: 'a-1',
    avsandare: 'kund',
    avsandareNamn: 'Birgitta Sandell',
    text: 'Min laptop har blivit väldigt långsam det senaste halvåret. Den tar ungefär fem minuter innan jag kan börja använda den efter att jag slagit på den, och sen hänger den sig när jag har flera flikar öppna i webbläsaren.',
    tidpunkt: timmarSedan(31),
    internt: false,
  },
  {
    id: 'm-2',
    arendeId: 'a-1',
    avsandare: 'assistent',
    avsandareNamn: 'Supportassistenten',
    text: 'Tack för din beskrivning. Jag har sammanfattat ärendet och skickat det vidare till en tekniker. Du får svar under kontorstid, normalt inom en arbetsdag.',
    tidpunkt: timmarSedan(31),
    internt: false,
  },
  {
    id: 'm-3',
    arendeId: 'a-1',
    avsandare: 'personal',
    avsandareNamn: 'Marcus Ek',
    text: 'Hej Birgitta,\n\nTack för att du hörde av dig. Det du beskriver stämmer väl med en hårddisk som börjar bli trött – det är mycket vanligt på datorer av den åldern och det brukar gå att åtgärda utan att du behöver köpa ny dator.\n\nInnan vi gör något vill jag gärna kontrollera hårddiskens hälsa. Passar det att jag ringer dig imorgon förmiddag så tar vi det över telefon? Det tar cirka 20 minuter.\n\nVänliga hälsningar\nMarcus, Nova IT',
    tidpunkt: timmarSedan(28),
    internt: false,
  },
  {
    id: 'm-4',
    arendeId: 'a-1',
    avsandare: 'personal',
    avsandareNamn: 'Marcus Ek',
    text: 'Skärmbilden från aktivitetshanteraren visar 100 % diskbelastning i vila. Stark indikation på döende mekanisk disk. Föreslår SSD 500 GB + 8 GB RAM. Viktigt: verifiera backup INNAN vi rör något, kunden har familjebilder som inte finns någon annanstans.',
    tidpunkt: timmarSedan(27),
    internt: true,
  },
  {
    id: 'm-5',
    arendeId: 'a-1',
    avsandare: 'kund',
    avsandareNamn: 'Birgitta Sandell',
    text: 'Hej Marcus, tack för snabbt svar! Imorgon förmiddag passar bra, jag är hemma hela dagen. Ring gärna på mobilen.',
    tidpunkt: timmarSedan(3),
    internt: false,
  },
  {
    id: 'm-6',
    arendeId: 'a-2',
    avsandare: 'kund',
    avsandareNamn: 'Peter Åkesson',
    text: 'Vårt kassasystem tappar kontakten med nätet flera gånger varje dag, framför allt mellan elva och två. Då kan vi inte ta kort och det blir kö direkt. Detta måste lösas snabbt.',
    tidpunkt: timmarSedan(26),
    internt: false,
  },
  {
    id: 'm-7',
    arendeId: 'a-2',
    avsandare: 'personal',
    avsandareNamn: 'Sofia Bergström',
    text: 'Hej Peter,\n\nJag förstår att det här påverkar er försäljning direkt, så vi prioriterar ärendet.\n\nMönstret du beskriver – att det uppstår just när det är mycket folk i lokalen – pekar mot att kassan konkurrerar om utrymme med gästernas mobiler på samma trådlösa nät. Det går att lösa genom att lägga kassan på ett eget, prioriterat nät.\n\nJag kan komma ut imorgon kl. 09:00, före lunchrusningen, och mäta upp läget på plats. Fungerar det?\n\nVänliga hälsningar\nSofia, Nova IT',
    tidpunkt: timmarSedan(24),
    internt: false,
  },
  {
    id: 'm-8',
    arendeId: 'a-2',
    avsandare: 'personal',
    avsandareNamn: 'Sofia Bergström',
    text: 'Snabb kanalskanning på distans via routerns webbgränssnitt: 2,4 GHz är helt packat, minst 14 nät på överlappande kanaler i fastigheten. Accesspunkten i köket står dessutom på auto och hoppar mellan kanal 1 och 6. Tar med mesh-enhet och gör en riktig mätning på plats.',
    tidpunkt: timmarSedan(23),
    internt: true,
  },
  {
    id: 'm-9',
    arendeId: 'a-2',
    avsandare: 'kund',
    avsandareNamn: 'Peter Åkesson',
    text: 'Perfekt, 09:00 imorgon fungerar. Jag är på plats då. Ring på sidodörren mot gården.',
    tidpunkt: timmarSedan(20),
    internt: false,
  },
  {
    id: 'm-10',
    arendeId: 'a-4',
    avsandare: 'kund',
    avsandareNamn: 'Ingrid Molin',
    text: 'Det kommer upp rutor hela tiden som säger att datorn är infekterad och att jag ska ringa ett nummer. Jag laddade ner ett program för att öppna en PDF igår. Jag har inte ringt numret.',
    tidpunkt: timmarSedan(5),
    internt: false,
  },
  {
    id: 'm-11',
    arendeId: 'a-4',
    avsandare: 'assistent',
    avsandareNamn: 'Supportassistenten',
    text: 'Du har gjort helt rätt i att inte ringa numret – sådana meddelanden är nästan alltid bedrägeriförsök. Undvik att använda internetbanken tills en tekniker har tittat på datorn. Ärendet har markerats som brådskande.',
    tidpunkt: timmarSedan(5),
    internt: false,
  },
  {
    id: 'm-12',
    arendeId: 'a-5',
    avsandare: 'kund',
    avsandareNamn: 'Helena Wikström',
    text: 'De nya konsulterna ser inte den delade brevlådan och kan inte öppna dokument i SharePoint-mappen för årsbokslut. Det är högsäsong så det är bråttom.',
    tidpunkt: tidsstampel(3, 8, 45),
    internt: false,
  },
  {
    id: 'm-13',
    arendeId: 'a-5',
    avsandare: 'personal',
    avsandareNamn: 'Sofia Bergström',
    text: 'Hej Helena,\n\nJag har tittat på behörigheterna. Båda kontona ligger utanför gruppen som ger åtkomst till den delade brevlådan och till bokslutsmappen – därför syns ingenting för dem.\n\nFör att jag ska kunna rätta det behöver jag att du godkänner min administratörsåtkomst i Microsoft 365. Du får en förfrågan via e-post från Microsoft, det räcker att du godkänner den. Sen är det åtgärdat inom en halvtimme.\n\nVänliga hälsningar\nSofia, Nova IT',
    tidpunkt: timmarSedan(6),
    internt: false,
  },
  {
    id: 'm-14',
    arendeId: 'a-5',
    avsandare: 'personal',
    avsandareNamn: 'Sofia Bergström',
    text: 'Väntar på att Helena godkänner delegerad administratörsbehörighet. Påminn imorgon om inget hänt – deadline för deklarationer gör att detta inte kan ligga.',
    tidpunkt: timmarSedan(6),
    internt: true,
  },
  {
    id: 'm-15',
    arendeId: 'a-6',
    avsandare: 'kund',
    avsandareNamn: 'Tomas Krister',
    text: 'Två av rummen har ingen uppkoppling alls i nätverksuttagen efter ombyggnaden. Wi-Fi fungerar men vi har stationära datorer där som behöver kabel.',
    tidpunkt: tidsstampel(5, 10, 15),
    internt: false,
  },
  {
    id: 'm-16',
    arendeId: 'a-6',
    avsandare: 'personal',
    avsandareNamn: 'Sofia Bergström',
    text: 'Hej Tomas,\n\nTack för bilden på serverskåpet, den var till stor hjälp. Utifrån den ser det ut som att ett par portar i patchpanelen inte är inkopplade till switchen – något som lätt händer vid en ombyggnation.\n\nJag behöver komma ut och testa kablarna för att veta säkert. Jag har en lucka på torsdag förmiddag.\n\nVänliga hälsningar\nSofia, Nova IT',
    tidpunkt: timmarSedan(74),
    internt: false,
  },
  {
    id: 'm-17',
    arendeId: 'a-6',
    avsandare: 'kund',
    avsandareNamn: 'Tomas Krister',
    text: 'Torsdag förmiddag går bra. Anmäl dig i receptionen så visar de vägen till korridoren med skåpet.',
    tidpunkt: timmarSedan(72),
    internt: false,
  },
  {
    id: 'm-18',
    arendeId: 'a-3',
    avsandare: 'kund',
    avsandareNamn: 'Lars Hedlund',
    text: 'Jag har köpt en ny stationär dator men vågar inte flytta över allt själv. Jag har bilder och dokument som jag absolut inte får tappa.',
    tidpunkt: tidsstampel(2, 13, 20),
    internt: false,
  },
  {
    id: 'm-19',
    arendeId: 'a-3',
    avsandare: 'personal',
    avsandareNamn: 'Marcus Ek',
    text: 'Hej Lars,\n\nDet ordnar vi. Vi tar det som ett hembesök så slipper du bära någon utrustning.\n\nUpplägget blir: vi säkerhetskopierar först allt från den gamla datorn, sedan sätter vi upp den nya, flyttar över dina filer, installerar Office och kopplar in skrivaren. Den gamla datorn lämnar vi orörd tills du själv har bekräftat att allt finns på plats.\n\nJag har bokat in oss på fredag kl. 13:00. Räkna med ungefär två timmar.\n\nVänliga hälsningar\nMarcus, Nova IT',
    tidpunkt: timmarSedan(48),
    internt: false,
  },
  {
    id: 'm-20',
    arendeId: 'a-8',
    avsandare: 'kund',
    avsandareNamn: 'Margareta Dahl',
    text: 'Föreningen har protokoll, medlemsregister och ett bildarkiv sedan 2009 på en gammal extern hårddisk. Vi vill ha en tryggare lösning men har begränsad budget.',
    tidpunkt: tidsstampel(7, 16, 30),
    internt: false,
  },
  {
    id: 'm-21',
    arendeId: 'a-8',
    avsandare: 'personal',
    avsandareNamn: 'Marcus Ek',
    text: 'Hej Margareta,\n\nEn enda hårddisk är en sårbar lösning – går den sönder är arkivet borta. Den vanliga tumregeln är minst två kopior på olika platser.\n\nJag har skissat på två alternativ med olika prisnivå och skickar en sammanställning under veckan. Eftersom medlemsregistret innehåller personuppgifter tar jag också med en kort not om vad ni behöver tänka på där.\n\nVänliga hälsningar\nMarcus, Nova IT',
    tidpunkt: timmarSedan(150),
    internt: false,
  },
  {
    id: 'm-22',
    arendeId: 'a-8',
    avsandare: 'personal',
    avsandareNamn: 'Marcus Ek',
    text: 'Ideell förening med liten budget – håll förslaget enkelt. Alternativ A: molnlagring 2 TB med versionshantering. Alternativ B: A + lokal NAS. Undvik att överdimensionera.',
    tidpunkt: timmarSedan(149),
    internt: true,
  },
  {
    id: 'm-23',
    arendeId: 'a-12',
    avsandare: 'kund',
    avsandareNamn: 'Tomas Krister',
    text: 'Vi får en ny driftstekniker som börjar om två veckor. Behöver en komplett arbetsplats innan hon börjar.',
    tidpunkt: tidsstampel(4, 11, 10),
    internt: false,
  },
  {
    id: 'm-24',
    arendeId: 'a-12',
    avsandare: 'personal',
    avsandareNamn: 'Marcus Ek',
    text: 'Hej Tomas,\n\nVi hinner gott. Jag har bokat in installationen hos oss i verkstaden så att datorn är helt färdig när hon kommer – konto, mejl, mappbehörigheter och fastighetssystemet.\n\nJag behöver bara hennes fullständiga namn och vilka mappar hon ska ha åtkomst till.\n\nVänliga hälsningar\nMarcus, Nova IT',
    tidpunkt: timmarSedan(40),
    internt: false,
  },
  {
    id: 'm-25',
    arendeId: 'a-9',
    avsandare: 'personal',
    avsandareNamn: 'Sofia Bergström',
    text: 'Hej Birgitta,\n\nNu ska sovrummet ha full täckning. Vi flyttade routern ut ur hallskåpet och satte en extra enhet i vardagsrummet.\n\nHör av dig om det krånglar igen.\n\nVänliga hälsningar\nSofia, Nova IT',
    tidpunkt: tidsstampel(21, 15),
    internt: false,
  },
]

// ─── Aktivitetslogg ─────────────────────────────────────────────────────────

export const demoAktiviteter: Aktivitet[] = [
  {
    id: 'akt-1',
    arendeId: 'a-1',
    typ: 'skapat',
    beskrivning: 'Ärendet skapades via supportassistenten',
    aktor: 'Supportassistenten',
    tidpunkt: timmarSedan(31),
  },
  {
    id: 'akt-2',
    arendeId: 'a-1',
    typ: 'tilldelning',
    beskrivning: 'Tilldelades Marcus Ek',
    aktor: 'Anna Lindqvist',
    tidpunkt: timmarSedan(30),
  },
  {
    id: 'akt-3',
    arendeId: 'a-1',
    typ: 'status',
    beskrivning: 'Status ändrades från Ny till Pågående',
    aktor: 'Marcus Ek',
    tidpunkt: timmarSedan(28),
  },
  {
    id: 'akt-4',
    arendeId: 'a-1',
    typ: 'meddelande',
    beskrivning: 'Svar skickat till kund',
    aktor: 'Marcus Ek',
    tidpunkt: timmarSedan(28),
  },
  {
    id: 'akt-5',
    arendeId: 'a-1',
    typ: 'anteckning',
    beskrivning: 'Intern anteckning tillagd',
    aktor: 'Marcus Ek',
    tidpunkt: timmarSedan(27),
  },
  {
    id: 'akt-6',
    arendeId: 'a-1',
    typ: 'meddelande',
    beskrivning: 'Nytt meddelande från kund',
    aktor: 'Birgitta Sandell',
    tidpunkt: timmarSedan(3),
  },
  {
    id: 'akt-7',
    arendeId: 'a-2',
    typ: 'skapat',
    beskrivning: 'Ärendet skapades via telefon',
    aktor: 'Anna Lindqvist',
    tidpunkt: timmarSedan(26),
  },
  {
    id: 'akt-8',
    arendeId: 'a-2',
    typ: 'prioritet',
    beskrivning: 'Prioritet ändrades från Hög till Kritisk',
    aktor: 'Anna Lindqvist',
    tidpunkt: timmarSedan(25),
  },
  {
    id: 'akt-9',
    arendeId: 'a-2',
    typ: 'tilldelning',
    beskrivning: 'Tilldelades Sofia Bergström',
    aktor: 'Anna Lindqvist',
    tidpunkt: timmarSedan(25),
  },
  {
    id: 'akt-10',
    arendeId: 'a-2',
    typ: 'meddelande',
    beskrivning: 'Svar skickat till kund',
    aktor: 'Sofia Bergström',
    tidpunkt: timmarSedan(24),
  },
  {
    id: 'akt-11',
    arendeId: 'a-2',
    typ: 'bokning',
    beskrivning: 'Hembesök bokat',
    aktor: 'Sofia Bergström',
    tidpunkt: timmarSedan(22),
  },
  {
    id: 'akt-12',
    arendeId: 'a-4',
    typ: 'skapat',
    beskrivning: 'Ärendet skapades via supportassistenten',
    aktor: 'Supportassistenten',
    tidpunkt: timmarSedan(5),
  },
  {
    id: 'akt-13',
    arendeId: 'a-4',
    typ: 'prioritet',
    beskrivning: 'Prioritet satt till Hög av supportassistenten',
    aktor: 'Supportassistenten',
    tidpunkt: timmarSedan(5),
  },
  {
    id: 'akt-14',
    arendeId: 'a-4',
    typ: 'bilaga',
    beskrivning: '2 bilagor mottagna från kund',
    aktor: 'Ingrid Molin',
    tidpunkt: timmarSedan(5),
  },
  {
    id: 'akt-15',
    arendeId: 'a-5',
    typ: 'skapat',
    beskrivning: 'Ärendet skapades via e-post',
    aktor: 'Helena Wikström',
    tidpunkt: tidsstampel(3, 8, 45),
  },
  {
    id: 'akt-16',
    arendeId: 'a-5',
    typ: 'status',
    beskrivning: 'Status ändrades från Pågående till Väntar på kund',
    aktor: 'Sofia Bergström',
    tidpunkt: timmarSedan(6),
  },
  {
    id: 'akt-17',
    arendeId: 'a-11',
    typ: 'skapat',
    beskrivning: 'Ärendet skapades via telefon',
    aktor: 'Anna Lindqvist',
    tidpunkt: timmarSedan(2),
  },
  {
    id: 'akt-18',
    arendeId: 'a-11',
    typ: 'prioritet',
    beskrivning: 'Prioritet satt till Kritisk',
    aktor: 'Anna Lindqvist',
    tidpunkt: timmarSedan(2),
  },
  {
    id: 'akt-19',
    arendeId: 'a-6',
    typ: 'skapat',
    beskrivning: 'Ärendet skapades via kontaktformuläret',
    aktor: 'Tomas Krister',
    tidpunkt: tidsstampel(5, 10, 15),
  },
  {
    id: 'akt-20',
    arendeId: 'a-6',
    typ: 'bokning',
    beskrivning: 'Platsbesök bokat till torsdag',
    aktor: 'Sofia Bergström',
    tidpunkt: timmarSedan(73),
  },
  {
    id: 'akt-21',
    arendeId: 'a-3',
    typ: 'bokning',
    beskrivning: 'Hembesök bokat',
    aktor: 'Marcus Ek',
    tidpunkt: timmarSedan(47),
  },
  {
    id: 'akt-22',
    arendeId: 'a-3',
    typ: 'status',
    beskrivning: 'Status ändrades från Pågående till Bokad',
    aktor: 'Marcus Ek',
    tidpunkt: timmarSedan(47),
  },
  {
    id: 'akt-23',
    arendeId: 'a-7',
    typ: 'skapat',
    beskrivning: 'Ärendet skapades via kontaktformuläret',
    aktor: 'Fredrik Sjöberg',
    tidpunkt: timmarSedan(11),
  },
  {
    id: 'akt-24',
    arendeId: 'a-9',
    typ: 'status',
    beskrivning: 'Status ändrades från Pågående till Löst',
    aktor: 'Sofia Bergström',
    tidpunkt: tidsstampel(21, 15),
  },
]

// ─── Bokningar ──────────────────────────────────────────────────────────────

export const demoBokningar: Bokning[] = [
  {
    id: 'bok-1',
    arendeId: 'a-2',
    arendenummer: 'NIT-2417',
    kundId: 'k-2',
    kundNamn: 'Café Vinden',
    typ: 'hembesok',
    status: 'bekraftad',
    datum: iDag,
    tid: '09:00',
    langdMinuter: 90,
    tekniker: 'u-3',
    plats: 'Bergslagsvägen 12, Vällingby',
    notering: 'Ring på sidodörren mot gården. Kanalanalys före lunchrusning.',
  },
  {
    id: 'bok-2',
    arendeId: 'a-1',
    arendenummer: 'NIT-2418',
    kundId: 'k-1',
    kundNamn: 'Birgitta Sandell',
    typ: 'telefonkontakt',
    status: 'bekraftad',
    datum: iDag,
    tid: '10:30',
    langdMinuter: 20,
    tekniker: 'u-2',
    plats: '070-412 88 31',
    notering: 'Genomgång av diskhälsa. Kunden är hemma hela dagen.',
  },
  {
    id: 'bok-3',
    arendeId: 'a-7',
    arendenummer: 'NIT-2424',
    kundId: 'k-7',
    kundNamn: 'Fredrik Sjöberg',
    typ: 'distanssupport',
    status: 'planerad',
    datum: iDag,
    tid: '14:00',
    langdMinuter: 45,
    tekniker: 'u-2',
    plats: 'Fjärranslutning',
    notering: 'Ominstallation av skrivardrivrutin.',
  },
  {
    id: 'bok-4',
    arendeId: 'a-3',
    arendenummer: 'NIT-2421',
    kundId: 'k-3',
    kundNamn: 'Lars Hedlund',
    typ: 'hembesok',
    status: 'bekraftad',
    datum: datumOm(2),
    tid: '13:00',
    langdMinuter: 120,
    tekniker: 'u-2',
    plats: 'Astrakangatan 7, Hässelby Gård',
    notering: 'Ta med extern disk för backup samt USB-hubb.',
  },
  {
    id: 'bok-5',
    arendeId: 'a-6',
    arendenummer: 'NIT-2419',
    kundId: 'k-6',
    kundNamn: 'Vällingby Fastighetsservice',
    typ: 'hembesok',
    status: 'bekraftad',
    datum: datumOm(3),
    tid: '08:30',
    langdMinuter: 180,
    tekniker: 'u-3',
    plats: 'Solursgången 3, Vällingby',
    notering: 'Anmäl dig i receptionen. Ta med kabeltestare och märkmaskin.',
  },
  {
    id: 'bok-6',
    arendeId: 'a-12',
    arendenummer: 'NIT-2420',
    kundId: 'k-6',
    kundNamn: 'Vällingby Fastighetsservice',
    typ: 'verkstadsbesok',
    status: 'planerad',
    datum: datumOm(6),
    tid: '11:00',
    langdMinuter: 150,
    tekniker: 'u-2',
    plats: 'Nova IT, verkstaden',
    notering: 'Förberedelse av arbetsplats till nyanställd.',
  },
  {
    id: 'bok-7',
    arendeId: 'a-5',
    arendenummer: 'NIT-2422',
    kundId: 'k-4',
    kundNamn: 'Bromma Redovisning',
    typ: 'distanssupport',
    status: 'planerad',
    datum: datumOm(1),
    tid: '15:30',
    langdMinuter: 30,
    tekniker: 'u-3',
    plats: 'Fjärranslutning',
    notering: 'Genomförs när delegerad administratörsbehörighet är godkänd.',
  },
  {
    id: 'bok-8',
    kundId: 'k-8',
    kundNamn: 'Hässelby Konstförening',
    typ: 'telefonkontakt',
    status: 'avbokad',
    datum: datumOm(-1),
    tid: '16:00',
    langdMinuter: 30,
    tekniker: 'u-2',
    plats: '08-38 44 21',
    notering: 'Avbokad av kunden, styrelsemöte flyttades.',
  },
]

// ─── Inställningar ──────────────────────────────────────────────────────────

export const demoKategorier: Arendekategori[] = [
  {
    id: 'kat-1',
    namn: 'Datorer och vardags-IT',
    nyckel: 'datorer_vardags_it',
    underkategorier: [
      'Prestanda och långsamhet',
      'Skrivare och kringutrustning',
      'Uppgradering av hårdvara',
      'Program och licenser',
    ],
    standardPrioritet: 'normal',
    aktiv: true,
  },
  {
    id: 'kat-2',
    namn: 'Nätverk och Wi-Fi',
    nyckel: 'natverk_wifi',
    underkategorier: [
      'Instabil anslutning',
      'Täckning och räckvidd',
      'Kabelnät och switchar',
      'Router och brandvägg',
    ],
    standardPrioritet: 'hog',
    aktiv: true,
  },
  {
    id: 'kat-3',
    namn: 'Konton, moln och säkerhet',
    nyckel: 'konton_moln_sakerhet',
    underkategorier: [
      'Microsoft 365 och behörigheter',
      'Tvåfaktorsautentisering',
      'Backup och återställning',
      'Google Workspace',
    ],
    standardPrioritet: 'hog',
    aktiv: true,
  },
  {
    id: 'kat-4',
    namn: 'Installation och flytt',
    nyckel: 'installation',
    underkategorier: ['Ny dator och dataflytt', 'Arbetsplats och onboarding', 'Kontorsflytt'],
    standardPrioritet: 'normal',
    aktiv: true,
  },
  {
    id: 'kat-5',
    namn: 'Virus och säkerhetsincident',
    nyckel: 'sakerhet_virus',
    underkategorier: ['Skadlig kod och varningar', 'Nätfiske', 'Intrångsmisstanke'],
    standardPrioritet: 'kritisk',
    aktiv: true,
  },
]

export const demoStandardsvar: Standardsvar[] = [
  {
    id: 'std-1',
    rubrik: 'Bekräftelse på mottaget ärende',
    kategori: 'Allmänt',
    text: 'Hej {{kundnamn}},\n\nTack för att du hörde av dig. Vi har tagit emot ditt ärende och en tekniker återkommer under kontorstid, normalt inom en arbetsdag.\n\nVänliga hälsningar\n{{tekniker}}, Nova IT',
  },
  {
    id: 'std-2',
    rubrik: 'Förslag på tid för hembesök',
    kategori: 'Bokning',
    text: 'Hej {{kundnamn}},\n\nJag föreslår att vi ses {{datum}} kl. {{tid}}. Räkna med ungefär {{langd}}.\n\nSvara gärna om tiden passar, annars hittar vi en annan.\n\nVänliga hälsningar\n{{tekniker}}, Nova IT',
  },
  {
    id: 'std-3',
    rubrik: 'Begäran om kompletterande uppgifter',
    kategori: 'Allmänt',
    text: 'Hej {{kundnamn}},\n\nFör att komma vidare behöver jag veta lite mer:\n\n– När uppstod problemet första gången?\n– Händer det varje gång eller ibland?\n– Har något ändrats i din utrustning nyligen?\n\nDu behöver inte kunna den tekniska orsaken, beskriv bara vad du märker.\n\nVänliga hälsningar\n{{tekniker}}, Nova IT',
  },
  {
    id: 'std-4',
    rubrik: 'Ärendet är åtgärdat',
    kategori: 'Avslut',
    text: 'Hej {{kundnamn}},\n\nNu ska allt fungera som det ska igen. Jag har åtgärdat {{atgard}}.\n\nHör av dig om något krånglar, då tittar vi på det utan extra kostnad inom 14 dagar.\n\nVänliga hälsningar\n{{tekniker}}, Nova IT',
  },
  {
    id: 'std-5',
    rubrik: 'Säkerhetsvarning – misstänkt bedrägeri',
    kategori: 'Säkerhet',
    text: 'Hej {{kundnamn}},\n\nDu har gjort helt rätt i att inte ringa numret eller lämna ut några uppgifter. Meddelanden av det slaget är nästan alltid bedrägeriförsök.\n\nAnvänd inte internetbank eller e-legitimation på datorn förrän vi har gått igenom den tillsammans.\n\nVänliga hälsningar\n{{tekniker}}, Nova IT',
  },
]

export const demoAviseringar: Aviseringsinstallning[] = [
  {
    id: 'avi-1',
    namn: 'Nytt ärende via kontaktformuläret',
    beskrivning: 'Avisera till gemensam inkorg när ett nytt ärende registreras.',
    aktiv: true,
  },
  {
    id: 'avi-2',
    namn: 'Nytt ärende via supportassistenten',
    beskrivning: 'Avisera direkt när assistenten skapar och sammanfattar ett ärende.',
    aktiv: true,
  },
  {
    id: 'avi-3',
    namn: 'Kritisk prioritet',
    beskrivning: 'Skicka omedelbar avisering till samtliga tekniker vid kritiskt ärende.',
    aktiv: true,
  },
  {
    id: 'avi-4',
    namn: 'Kundsvar på öppet ärende',
    beskrivning: 'Avisera ansvarig tekniker när kunden svarar.',
    aktiv: true,
  },
  {
    id: 'avi-5',
    namn: 'Påminnelse om ärenden utan svar',
    beskrivning: 'Daglig sammanställning av ärenden som varit obesvarade i mer än 24 timmar.',
    aktiv: true,
  },
  {
    id: 'avi-6',
    namn: 'Påminnelse om bokning till kund',
    beskrivning: 'Skicka påminnelse via e-post dagen före bokat besök.',
    aktiv: false,
  },
  {
    id: 'avi-7',
    namn: 'Veckorapport till verksamhetsansvarig',
    beskrivning: 'Sammanfattning av lösta ärenden och svarstider varje måndag.',
    aktiv: false,
  },
]

export const demoMottagare: EpostMottagare[] = [
  { id: 'mot-1', epost: 'kontakt@nova-it.se', syfte: 'Gemensam inkorg, alla nya ärenden', aktiv: true },
  { id: 'mot-2', epost: 'anna@nova-it.se', syfte: 'Kritiska ärenden och veckorapport', aktiv: true },
  { id: 'mot-3', epost: 'marcus@nova-it.se', syfte: 'Tilldelade ärenden och bokningar', aktiv: true },
  { id: 'mot-4', epost: 'sofia@nova-it.se', syfte: 'Tilldelade ärenden, nätverk', aktiv: true },
  { id: 'mot-5', epost: 'faktura@nova-it.se', syfte: 'Underlag för fakturering', aktiv: false },
]
