/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TjansterRouteImport } from './routes/tjanster'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AssistentRouteImport } from './routes/assistent'
import { Route as IndexRouteImport } from './routes/index'

const TjansterRoute = TjansterRouteImport.update({
  id: '/tjanster',
  path: '/tjanster',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistentRoute = AssistentRouteImport.update({
  id: '/assistent',
  path: '/assistent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistent': typeof AssistentRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/tjanster': typeof TjansterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistent': typeof AssistentRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/tjanster': typeof TjansterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistent': typeof AssistentRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/tjanster': typeof TjansterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/assistent' | '/faq' | '/kontakt' | '/om-oss' | '/tjanster'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assistent' | '/faq' | '/kontakt' | '/om-oss' | '/tjanster'
  id:
    | '__root__'
    | '/'
    | '/assistent'
    | '/faq'
    | '/kontakt'
    | '/om-oss'
    | '/tjanster'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistentRoute: typeof AssistentRoute
  FaqRoute: typeof FaqRoute
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  TjansterRoute: typeof TjansterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tjanster': {
      id: '/tjanster'
      path: '/tjanster'
      fullPath: '/tjanster'
      preLoaderRoute: typeof TjansterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistent': {
      id: '/assistent'
      path: '/assistent'
      fullPath: '/assistent'
      preLoaderRoute: typeof AssistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistentRoute: AssistentRoute,
  FaqRoute: FaqRoute,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  TjansterRoute: TjansterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
