/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TjansterRouteImport } from './routes/tjanster'
import { Route as ProjektAterbrukRouteImport } from './routes/projekt-aterbruk'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CaseStudyRouteImport } from './routes/case-study'
import { Route as AssistentRouteImport } from './routes/assistent'
import { Route as ArbetssattRouteImport } from './routes/arbetssatt'
import { Route as IndexRouteImport } from './routes/index'

const TjansterRoute = TjansterRouteImport.update({
  id: '/tjanster',
  path: '/tjanster',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektAterbrukRoute = ProjektAterbrukRouteImport.update({
  id: '/projekt-aterbruk',
  path: '/projekt-aterbruk',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudyRoute = CaseStudyRouteImport.update({
  id: '/case-study',
  path: '/case-study',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistentRoute = AssistentRouteImport.update({
  id: '/assistent',
  path: '/assistent',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbetssattRoute = ArbetssattRouteImport.update({
  id: '/arbetssatt',
  path: '/arbetssatt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arbetssatt': typeof ArbetssattRoute
  '/assistent': typeof AssistentRoute
  '/case-study': typeof CaseStudyRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/projekt-aterbruk': typeof ProjektAterbrukRoute
  '/tjanster': typeof TjansterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arbetssatt': typeof ArbetssattRoute
  '/assistent': typeof AssistentRoute
  '/case-study': typeof CaseStudyRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/projekt-aterbruk': typeof ProjektAterbrukRoute
  '/tjanster': typeof TjansterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arbetssatt': typeof ArbetssattRoute
  '/assistent': typeof AssistentRoute
  '/case-study': typeof CaseStudyRoute
  '/faq': typeof FaqRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/projekt-aterbruk': typeof ProjektAterbrukRoute
  '/tjanster': typeof TjansterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arbetssatt'
    | '/assistent'
    | '/case-study'
    | '/faq'
    | '/kontakt'
    | '/om-oss'
    | '/projekt-aterbruk'
    | '/tjanster'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arbetssatt'
    | '/assistent'
    | '/case-study'
    | '/faq'
    | '/kontakt'
    | '/om-oss'
    | '/projekt-aterbruk'
    | '/tjanster'
  id:
    | '__root__'
    | '/'
    | '/arbetssatt'
    | '/assistent'
    | '/case-study'
    | '/faq'
    | '/kontakt'
    | '/om-oss'
    | '/projekt-aterbruk'
    | '/tjanster'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArbetssattRoute: typeof ArbetssattRoute
  AssistentRoute: typeof AssistentRoute
  CaseStudyRoute: typeof CaseStudyRoute
  FaqRoute: typeof FaqRoute
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  ProjektAterbrukRoute: typeof ProjektAterbrukRoute
  TjansterRoute: typeof TjansterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tjanster': {
      id: '/tjanster'
      path: '/tjanster'
      fullPath: '/tjanster'
      preLoaderRoute: typeof TjansterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekt-aterbruk': {
      id: '/projekt-aterbruk'
      path: '/projekt-aterbruk'
      fullPath: '/projekt-aterbruk'
      preLoaderRoute: typeof ProjektAterbrukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study': {
      id: '/case-study'
      path: '/case-study'
      fullPath: '/case-study'
      preLoaderRoute: typeof CaseStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistent': {
      id: '/assistent'
      path: '/assistent'
      fullPath: '/assistent'
      preLoaderRoute: typeof AssistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbetssatt': {
      id: '/arbetssatt'
      path: '/arbetssatt'
      fullPath: '/arbetssatt'
      preLoaderRoute: typeof ArbetssattRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArbetssattRoute: ArbetssattRoute,
  AssistentRoute: AssistentRoute,
  CaseStudyRoute: CaseStudyRoute,
  FaqRoute: FaqRoute,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  ProjektAterbrukRoute: ProjektAterbrukRoute,
  TjansterRoute: TjansterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
